### ISSUE TITLE
Missing tag for version twitch4j-1.0.0-alpha.19/

### ISSUE THREAD

**Issue by asbachb** [twitch4j/twitch4j#106]
Seems the tag for latest alpha release [1] is missing on github.

[1] https://oss.jfrog.org/artifactory/libs-release/com/github/twitch4j/twitch4j/1.0.0-alpha.19/

**Comment by PhilippHeuer** [comment]
Pushed the missing tag and wrote the release notes: https://github.com/twitch4j/twitch4j/releases/tag/v1.0.0-alpha.19

Thanks for the report.
