### ISSUE TITLE
[DOCS] FatJar Download

### ISSUE THREAD

**Issue by Skillkiller** [twitch4j/twitch4j#108]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [X] This issue specifically has something to do with Twitch4J
* [X] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description
Hey,
in the documentation the FatJar download link points to the localhost :)
You can find the source here: https://github.com/twitch4j/twitch4j/blob/master/docs/content/getting-started/installation.md in Line 52.

Greetings,
Skillkiller

**Comment by PhilippHeuer** [comment]
I removed this from the docs since we're not providing a fatJar right now.
