### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by PhilippHeuer** [twitch4j/twitch4j#11]
### Description
* Adding integration tests for all official/unofficial api endpoints.
* Split Unit Tests and Integration Tests to run separately
* Run integration test's for master frequently, regardlesss of builds (for notifications)

### Additional Information
Integration tests are useful to test if any functionality is broken, especially since this api also provides access to unofficial endpoints (which can change without notice).

**Comment by stachu540** [comment]
* API test will use **Mockito** framework for testing **POJO** formatting via **Jackson** and exception testing.
* TMI (Twitch Message Interface) will be tested while connected into the bot channel chat and testing channel messaging, chat rooms and private messages. Also will testing parser aswell.
* PubSub will be simmilar like above. But will be testing POJO Parsing and their exceptions.
