### ISSUE TITLE
All Thread creation should use a ScheduledExecutor and be customizeable

### ISSUE THREAD

**Issue by boostchicken** [twitch4j/twitch4j#111]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [x] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description
Threading is uncontrollable, and not done with Java best practices in mind.  Currently, Threads are running forever and slept as opposed to scheduled and executed and then destroyed.  Also, I have no ability to customize when these threads are run or to have them participate in Thread Pool my application has already created.

### Solutions

Use ScheduledThreadPoolExecutor everywhere (PubSub, ClientHelper etc)
Allow us to provide our own Executor
Allow us to configure how often all tasks are ran

**Comment by boostchicken** [comment]
https://github.com/twitch4j/twitch4j/pull/110

Fix for ClientHelper

**Comment by boostchicken** [comment]
An Example:
```
try {
                    // check if we need to send a PING (every 4 minutes, disconnect after 5 minutes without sending ping)
                    if (TimeUtils.getCurrentTimeInMillis() - lastPing > 4 * 60 * 1000) {
                        PubSubRequest request = new PubSubRequest();
                        request.setType(PubSubType.PING);
                        sendCommand(TypeConvert.objectToJson(request));

                        log.debug("PubSub: Sending PING!");
                        lastPing = TimeUtils.getCurrentTimeInMillis();
                    }

                    // check for missing pong response
                    if (TimeUtils.getCurrentTimeInMillis() >= lastPing + 10000 && lastPong < lastPing) {
                        log.warn("PubSub: Didn't receive a PONG response in time, reconnecting to obtain a connection to a different server.");
                        reconnect();
                    }

                    // If connected, send one message from the queue
                    if (commandQueue.size() > 0) {
                        if (connectionState.equals(TMIConnectionState.CONNECTED)) {
                            // pop one command from the queue and execute it
                            String command = commandQueue.remove();
                            sendCommand(command);

                            // Logging
                            log.debug("Processed command from queue: [{}].", command);
                        }
                    }

                    // sleep one second
                    Thread.sleep(1000);
                } catch (Exception ex) {
                    log.error("PubSub: Unexpected error in worker thread", ex);
                }
```

This thread is started and run forever, then slept for 1000 milliseconds, beyond that it does two different jobs.  One is the heartbeat, the other is actually sending commands.  If one fails they both do

With a scheduled thread pool executor, we would schedule to different tasks.  This was, one would not affect the other, performance or timing-wise.
1. Heartbeat - Run every 4 minutes
2. Send Command - Run every second.

As opposed to always having a thread running taking up resources, these threads would be executed against a thread in a threadpool and there would be no Thread.sleep involved or never-ending while loop.  Then the ScheduledExecutor will execute each task on an existing thread from its thread pool when the correct time comes

Also, most applications usually have their own thread pool configured.  They are tuned to meet the constraints of their CPU resources and also their behavior is tuned to meet the requirements of their application. All thread-based tasks should accept an Executor from the user, if that is not supplied twitch4j should create one of its own, that is shared for ALL twitch4j tasks (Pubsub, Client Helper, Creds).

**Comment by PhilippHeuer** [comment]
Thanks for the issue and the great explaination, lets use this to track progress for this change overall.

- [x] TwitchClientHelper
- [ ] PubSub
- [ ] Chat

**Comment by boostchicken** [comment]
@PhilippHeuer Do you want to close this issue now, or wait for release? All the work should have been done.

**Comment by PhilippHeuer** [comment]
Lets close this issue as everything was merged into `develop` - thanks again :)
