### ISSUE TITLE
StreamEventListener not always working

### ISSUE THREAD

**Issue by FocusZTV** [twitch4j/twitch4j#113]
I am using Twitch4J for a Live Alerts feature of my Discord Bots. I have enabled the StreamEventListener for all of the streamer's names, and when the code runs, it adds them all with a 2-second wait in between each one. 

This does not always work, and my ChannelGoLiveEvent is not always triggered when someone goes live. It does work sometimes, but not other times.

**Expected behavior:** 
Event to be triggered when someone goes live

**Actual behavior:** 
Event is not always triggered

**Version affected:** 
1.0.0-alpha.19

**Comment by FocusZTV** [comment]
Fixed the issue myself.

**Comment by Maxouxax** [comment]
Can you give more details about the issue you were facing and how you solved it by yourself ?
