### ISSUE TITLE
Access Tokens

### ISSUE THREAD

**Issue by FocusZTV** [twitch4j/twitch4j#115]
Please add a feature to allow getting access tokens from twitch, and the ability for the library to use them in TwitchClientHelper. 

I realized there is no way to use a token in the TwitchClientHelper, and when I run my program I get 401 errors from the Twitch API saying the "OAuth token is missing". And looking at the source code, it just uses null as the token.

Thanks

**Comment by PhilippHeuer** [comment]
The credential used by the TwitchClientHelper is set via 

```
TwitchClient twitchClient = TwitchClientBuilder.builder()
...
            .withDefaultAuthToken(new OAuth2Credential("twitch", "oauthtokenhere"))
...
            .build();
```

**Comment by FocusZTV** [comment]
> The credential used by the TwitchClientHelper is set via
> 
> ```
> TwitchClient twitchClient = TwitchClientBuilder.builder()
> ...
>             .withDefaultAuthToken(new OAuth2Credential("twitch", "oauthtokenhere"))
> ...
>             .build();
> ```

I am using the latest version of Twitch4J (1.0.0-alpha.19), and that method does not exist in the TwitchClientBuilder. What am I supposed to do?

**Comment by iProdigy** [comment]
You can now update to `1.0.0-alpha.20`

**Comment by FocusZTV** [comment]
Ok, thanks.

Now I am facing another issue, where I enable one ChannelGoLiveEvent, but the event gets triggered more than once. Why is this happening?
