### ISSUE TITLE
ChannelGoLiveEvent Triggering more than once

### ISSUE THREAD

**Issue by FocusZTV** [twitch4j/twitch4j#120]
I recently updated to version 1.0.0-alpha.20 and am now having an issue where the ChannelGoLiveEvent is triggered more than once.

I have only been facing this issue after updating from 1.0.0-alpha.19, and it is not related to the Twitch API. It is nothing to do with streamers streams freezing, the event gets triggered up to 10 times in the matter of a few seconds for one streamer, and even triggers after they end stream sometimes.

Could this be fixed? It is also nothing to do with my code, as I have not changed any of that stuff for about a year, and have never had a problem before. Thanks

**Comment by iProdigy** [comment]
Is the number of channels you're sending to the stream event listener in the ballpark of 10?

**Comment by FocusZTV** [comment]
> Is the number of channels you're sending to the stream event listener in the ballpark of 10?

What do you mean by this? 

When my program starts up, it adds a list of streamers names 1 by 1 to the TwitchClientHelper, with a 2-second delay between adding each one. The same as I had it on the previous version with no issues.

**Comment by sp0ck1** [comment]
How many streamers are in the "list of streamers names" is what he meant, and is the number around 10 by chance?

**Comment by FocusZTV** [comment]
> How many streamers are in the "list of streamers names" is what he meant, and is the number around 10 by chance?

There are 15 streamers on the list. I don't understand how this could cause an issue though?

**Comment by condolent** [comment]
Happens to me as well, only  have one channel that I listen to and when I go offline, it triggers GoLive, then GoOffline two times
