### ISSUE TITLE
TwitchClientHelper allow more than 100 channels to be added for GoLiveEvent

### ISSUE THREAD

**Issue by condolent** [twitch4j/twitch4j#121]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [x] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description

As my application is growing I've noticed that it now has stopped working since I'm making too many requests. I'm using the `ChannelGoLiveEvent` and I need more than 100  channels to listen to. Just over 500 to be exact.

### Solutions

If I've  done `twitchClient.getClientHelper().enableStreamEventListener("channel");` more than 100 times, then split the list `listenForGoLive` and inside the Client Helper send  the request multiple times with the splitted lists, to support more than 100 channels.

### Alternatives

I've tried using the `TwitchClientHelper` class to try to replicate the function and modify it myself, but I can't seem to  make it work. However I  am sure this is due to the limits of my  Java knowledge. I'm sure anyone with more knowledge would be able to do this quite easy.

**Comment by JellyBrick** [comment]
My solution (temporary fix)

```kotlin
private val eventManager = EventManager().apply {
  registerEventHandler(SimpleEventHandler())
}

...

  val twitchClientOne = buildTwitchClient()
  val twitchClientTwo = buildTwitchClient()
  eventManager.getEventHandler(SimpleEventHandler::class.java).onEvent(ChannelGoLiveEvent::class.java, eventHandler)

...

private fun buildTwitchClient(): TwitchClient {
  TwitchClientBuilder.builder()
    .withClientId(clientId)
    .withClientSecret(clientSecret)
    .withEnableHelix(true)
    .withEventManager(eventManager)
    .build()
}
```

**Comment by condolent** [comment]
@JellyBrick I tried that before but must've done it incorrectly. When I tried it again by a different method it works fine. Thanks
