### ISSUE TITLE
ChannelGoLiveEvent doesn't fire in alpha 22

### ISSUE THREAD

**Issue by condolent** [twitch4j/twitch4j#126]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [X] This issue specifically has something to do with Twitch4J
* [X] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description
When using the recent build from the development branch, `1.0.0-alpha.22`, events like ChannelGoLiveEvent and ChannelGoOfflineEvent doesn't fire at all. Not even when there's only one single channel that's being tracked.

### Steps to Reproduce
1. Add a twitch channel to listener with `twitchClient.getClientHelper().enableStreamEventListener("mychannel");`
2. Go live on twitch

---

**Expected behavior:** 
ChannelGoLiveEvent triggered.

**Actual behavior:** 
Nothing, no logs or anything.

**Stacktrace (if applicable):** 

**Version affected:** 
1.0.0-alpha.22

**Comment by condolent** [comment]
This was sadly not fixed in #124 & #127 
Still an issue in `1.0.0-alpha.23`

**Comment by FocusZTV** [comment]
Could this be fixed? Where can I even find the latest version to use?

**Comment by condolent** [comment]
@FocusZTV this will be fixed in #128 
Once merged into `develop` you can use `1.0.0-alpha.24` in your pom.xml

**Comment by condolent** [comment]
Fixed by #128 !
