### ISSUE TITLE
.getStreams() returns an sometimes returns an empty list

### ISSUE THREAD

**Issue by FocusZTV** [twitch4j/twitch4j#137]
I am using TwitchClientHelper in my project, and have it set up to listen for about 15 channels to go live. All issues with that not working are fixed, but now I have another issue.

In the ChannelGoLiveEvent method, it is supposed to get the User and the Stream, but the Stream sometimes returns an empty list? I was wondering if this is to do with rate-limiting, or if this is another issue.

And to be clear, when it doesn't work, it is nothing to do with the streamer. It randomly doesn't work, and it could be any streamer. I am using version 1.0.0-alpha.24, and am using a valid Twitch API token in both the .getUsers() and .getStreams() methods.

Thanks

**Comment by condolent** [comment]
Can you show the code that doesn't work?

**Comment by FocusZTV** [comment]
Here is the code, which is inside the ChannelGoLiveEvent method. 

https://pastebin.com/NfJA0WfC

**Comment by FocusZTV** [comment]
I am also in the Discord server. Should I just put this in one of the help channels there?
