### ISSUE TITLE
Crash when requesting anything

### ISSUE THREAD

**Issue by Dyskal** [twitch4j/twitch4j#139]
Hello, I have a problem with twitch4j, whenever i try something, it crash with this stacktrace: 
https://pastebin.com/aMnCR201
the code is: (twitch4j version alpha.20)
```java
import com.github.twitch4j.TwitchClient;
import com.github.twitch4j.TwitchClientBuilder;
import com.github.twitch4j.helix.domain.StreamList;

public class ui {
    public static void main(String[] args) {
        TwitchClient twitchClient = TwitchClientBuilder.builder().withEnableHelix(true).build();
        StreamList resultList = twitchClient.getHelix().getStreams("", "", null, 5, null, null, null, null, null).execute();
        resultList.getStreams().forEach(stream -> System.out.println("ID: " + stream.getId() + " - Title: " + stream.getTitle()));
    }
}
```

**Comment by iProdigy** [comment]
For the first argument to `TwitchHelix#getStreams` you need to provide a valid access token. Also, you can update to alpha.24

**Comment by Dyskal** [comment]
how can i get an access token ?

**Comment by iProdigy** [comment]
You can use a tool like [twitchtokengenerator](https://twitchtokengenerator.com/) or [do it manually](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth)

**Comment by Dyskal** [comment]
thanks, i did it manually because i need an app auth token and not a user auth token
