### ISSUE TITLE
TwitchChat timeout function malformed

### ISSUE THREAD

**Issue by charlescohen7** [twitch4j/twitch4j#156]
Hello everyone,

Thank you for this library :)

I found a little bug on the `timeout(String channel, String user, Duration duration, String reason)` function that makes it not working.

The current function `timeout("channel", "charles", Duration.ofSeconds(600), "")` returns `/timeout charles600` because there is a missing space in the StringBuilder : 

`StringBuilder sb = new StringBuilder(user).append(duration.getSeconds());` should be `StringBuilder sb = new StringBuilder(user).append(" ").append(duration.getSeconds());`

Have a nice day :)

**Comment by PhilippHeuer** [comment]
We merged a fix for this together with #155 into develop, will be fixed in `1.0.1+`

**Comment by charlescohen7** [comment]
Nice !
