### ISSUE TITLE
Auth: allow scoped app access tokens to be created

### ISSUE THREAD

**Issue by iProdigy** [twitch4j/twitch4j#201]
### Description
App access tokens with scopes *can* be useful in specific applications (e.g. requesting analytics data). The library currently can only provide an app access token with no scopes.

### Solutions
Be able to specify scopes to be included when creating an app access token. This code should go in TwitchIdentityProvider (see https://github.com/twitch4j/twitch4j/pull/140/files#diff-71a23df8202e1cc7645f26ea53b70879 for a first attempt)

### Alternatives
Could put the bulk of the logic in https://github.com/PhilippHeuer/credential-manager/blob/master/src/main/java/com/github/philippheuer/credentialmanager/identityprovider/OAuth2IdentityProvider.java instead

**Comment by youngkaneda** [comment]
@iProdigy I would like to work on this, can you assigne to me?

**Comment by iProdigy** [comment]
Analytics no longer needs scoped app access
