### ISSUE TITLE
Kraken: Add Collections Endpoints

### ISSUE THREAD

**Issue by iProdigy** [twitch4j/twitch4j#202]
### Description
The following endpoints have not yet been added to Helix (latest status is that twitch is simply investigating including them or not):

- [x] Get Collection Metadata
- [x] Get Collection
- [x] Get Collections by Channel
- [x] Create Collection
- [x] Update Collection
- [x] Create Collection Thumbnail
- [x] Delete Collection
- [x] Add Item to Collection
- [x] Delete Item from Collection
- [x] Move Item within Collection

### Solutions
Implement these endpoints in `TwitchKraken`

### Alternatives
Wait and see if a helix analog will be released

### Additional Information
Official documentation: https://dev.twitch.tv/docs/v5/reference/collections

**Comment by p4czyk** [comment]
Just began working on that issue! 🚀
