### ISSUE TITLE
ChannelMessageEvent event.reply() method

### ISSUE THREAD

**Issue by EclipseKnight** [twitch4j/twitch4j#245]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [x] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description
An example for my situation is the twitch/discord bot I'm creating. The JDA utilities library has a ```event.reply()``` [method](https://github.com/JDA-Applications/JDA-Utilities/blob/271be3bd42c3fe8e1b289dfd1f308209eb857a3a/command/src/main/java/com/jagrosh/jdautilities/command/CommandEvent.java#L149) for its CommandEvent. 

It cuts down the characters and makes the line of code much cleaner than the current Twitch4j method which requires you to do the following: ```event.getTwitchChat().sendMessage(event.getChannel().getName(), message)```.

### Solutions
As stated in the description, having a simple ```event.reply()``` method for the ChannelMessageEvent would simplify the code. 
From the user end it is pretty difficult to make this implementation. I myself just created a simple static utility method to simplify it more than normal rather than attempt the implementation: 

```
public static void sendMessage(ChannelMessageEvent event, String message) {
	event.getTwitchChat().sendMessage(event.getChannel().getName(), message);
}
```

### Alternatives
I guess I kinda pointed one out in the solutions. 

### Additional context
nah that's about it. Thanks!

**Comment by iProdigy** [comment]
@PhilippHeuer Should we: 

1. Store a reference to the relevant `TwitchChat` instance within `IRCMessageEvent`
2. Define the method signature as so: `ChannelMessageEvent#reply(TwitchChat, String)`
3. Just use `TwitchEvent#getTwitchChat` and not worry about which instance is returned (as there could be multiple `TwitchChat` instances)

I think `#2` should be done (note that some bots could have multiple anonymous `TwitchChat` instances for *reading* but *one* authenticated `TwitchChat` instance for *sending*, so they'd want to pass the authenticated instance to such a method), but should we also have an overloaded version where we implement `#1` so manually passing the `TwitchChat` instance isn't needed (which would suffice for the vast majority of applications)?
