### ISSUE TITLE
Migration repository to Maven Central

### ISSUE THREAD

**Issue by stachu540** [twitch4j/twitch4j#269]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [x] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description
The JCenter repository going shuts down **May 1st**. Before in fact submissions will be accepted till ~~**Feburay 28th**~~ **April 1st**, after that there will be ***NO more relases*** in JCenter. Unfortunate previous releases will be mostly suffer, because there will be not able to download oldest releases after sunset.

### Solutions
Following by [this guide](https://central.sonatype.org/pages/ossrh-guide.html)
 - Create GPG Key
 - Create `com.github.twitch4j` namespace
 - Implement GPG Key and Passphrase into CI

### Alternatives
~~Use [Jitpack](https://jitpack.io/) to distribute repository / hosting to [GitHub Packages](https://github.com/features/packages/)~~ - no more alts. Starting deploy central **April 1st**.

### Additional context
Reference topic: <https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/>

**Comment by stachu540** [comment]
Affected packages:
- `com.github.phillipheuer`

Recommend: Merge to this repository.

**Comment by PhilippHeuer** [comment]
The credentialManager + events4j will move to central too. Those are the only projects in com.github.philipheuer if i remember correctly.

- https://issues.sonatype.org/browse/OSSRH-43568
- https://issues.sonatype.org/browse/OSSRH-43570

**Comment by stachu540** [comment]
Using [this following](https://dev.to/kengotoda/deploying-to-ossrh-with-gradle-in-2020-1lhi) solutions, I will starting test it my repos. Honestly, I was getting used to it with the jcenter repo.

**Comment by stachu540** [comment]
Resolved in #243 and #229
