### ISSUE TITLE
 I would like to consult active users in the chat

### ISSUE THREAD

**Issue by marcosebs** [twitch4j/twitch4j#278]
Good afternoon,

Currently I use the TMI API to receive all Chatters, however I would like to receive or be able to filter only those who are actually watching, I would like to know if it is possible to search only the users who are running live at the time of the search.

**Comment by iProdigy** [comment]
Unfortunately this is a limitation of the API that Twitch4J cannot work around. Instead, the closest you could get is creating a video overlay extension that informs your EBS whether a user has the livestream running (but even this isn't a silver bullet). For loyalty systems, you could check whether a chatter has sent a message in the last x minutes.
