### ISSUE TITLE
Warning in Parsing PubSub (ANON_SUB_GIFT)

### ISSUE THREAD

**Issue by Doc94** [twitch4j/twitch4j#289]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [x] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description
In the last version 1.2.1 in anonsubgif have a warning in parsing.

### Steps to Reproduce
1. Listen for Sub Events in PubSub

---

**Expected behavior:** 

Listen for sub in PubSub

**Actual behavior:** 

When a ANON_SUB_GIFT happen the system show a warning
`PubSub: Unparsable Message: {"type":"MESSAGE","data":{"topic":"channel-subscribe-events-v1.30610294","message":"{\"benefit_end_month\":0,\"channel_name\":\"jaidefinichon\",\"channel_id\":\"30610294\",\"recipient_id\":\"432295091\",\"recipient_user_name\":\"tomymon_r\",\"recipient_display_name\":\"Tomymon_r\",\"time\":\"2021-03-04T21:36:31.270149021Z\",\"sub_message\":{\"message\":\"\",\"emotes\":null},\"sub_plan\":\"1000\",\"sub_plan_name\":\"Sub del GOI\",\"months\":3,\"context\":\"anonsubgift\",\"is_gift\":true,\"multi_month_duration\":1}"}}

 - [Value of answer is mandatory]`

**Stacktrace (if applicable):** 

```
18:36:31.908 [ReadingThread] WARN  |c.g.twitch4j.pubsub.TwitchPubSub| - PubSub: Unparsable Message: {"type":"MESSAGE","data":{"topic":"channel-subscribe-events-v1.30610294","message":"{\"benefit_end_month\":0,\"channel_name\":\"jaidefinichon\",\"channel_id\":\"30610294\",\"recipient_id\":\"432295091\",\"recipient_user_name\":\"tomymon_r\",\"recipient_display_name\":\"Tomymon_r\",\"time\":\"2021-03-04T21:36:31.270149021Z\",\"sub_message\":{\"message\":\"\",\"emotes\":null},\"sub_plan\":\"1000\",\"sub_plan_name\":\"Sub del GOI\",\"months\":3,\"context\":\"anonsubgift\",\"is_gift\":true,\"multi_month_duration\":1}"}}


 - [Value of answer is mandatory]


18:36:32.018 [ReadingThread] WARN  |io.sentry.DefaultSentryClientFactory| - No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames


18:36:32.029 [ReadingThread] WARN  |io.sentry.DefaultSentryClientFactory| - No 'stacktrace.app.packages' was configured, this option is highly recommended as it affects stacktrace grouping and display on Sentry. See documentation: https://docs.sentry.io/clients/java/config/#in-application-stack-frames


java.lang.IllegalArgumentException: Value of answer is mandatory


	at io.github.stepio.jgforms.answer.Validation.fail(Validation.java:143)


	at io.github.stepio.jgforms.answer.Validation.isTrue(Validation.java:132)


	at io.github.stepio.jgforms.answer.Validation.notNull(Validation.java:120)


	at io.github.stepio.jgforms.answer.Builder.put(Builder.java:193)


	at me.mrdoc.twitch.subtracker.classes.TwitchInstance.sendSubToForm(TwitchInstance.java:155)


	at me.mrdoc.twitch.subtracker.classes.TwitchInstance.onSub(TwitchInstance.java:69)


	at com.github.philippheuer.events4j.simple.SimpleEventHandler.lambda$publish$3(SimpleEventHandler.java:102)


	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)


	at com.github.philippheuer.events4j.simple.SimpleEventHandler.publish(SimpleEventHandler.java:102)


	at com.github.philippheuer.events4j.core.EventManager.lambda$publish$0(EventManager.java:160)


	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)


	at com.github.philippheuer.events4j.core.EventManager.publish(EventManager.java:160)


	at com.github.twitch4j.pubsub.TwitchPubSub$1.onTextMessage(TwitchPubSub.java:377)


	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:353)


	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:266)


	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:244)


	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:969)


	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:752)


	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)


	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)


	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Version affected:** 

1.2.1

**Comment by duncte123** [comment]
getting the same here for a mod event in version 1.5.0

```json
Unparsable Message: MESSAGE|PubSubResponsePayload(
topic=chat_moderator_actions.711909329.91097747, 
message=PubSubResponsePayloadMessage(type=moderator_removed, messageData {"channel_id":"91097747","target_user_id":"711909329","moderation_action":"unmod","target_user_login":"dunctebot","created_by_user_id":"91097747","created_by":"duncte123"}, 
rawMessage={"type":"moderator_removed","data":{"channel_id":"91097747","target_user_id":"711909329","moderation_action":"unmod","target_user_login":"dunctebot","created_by_user_id":"91097747","created_by":"duncte123"}}))
```

**Comment by Doc94** [comment]
> getting the same here for a mod event in version 1.5.0
> 
> ```json
> Unparsable Message: MESSAGE|PubSubResponsePayload(
> topic=chat_moderator_actions.711909329.91097747, 
> message=PubSubResponsePayloadMessage(type=moderator_removed, messageData {"channel_id":"91097747","target_user_id":"711909329","moderation_action":"unmod","target_user_login":"dunctebot","created_by_user_id":"91097747","created_by":"duncte123"}, 
> rawMessage={"type":"moderator_removed","data":{"channel_id":"91097747","target_user_id":"711909329","moderation_action":"unmod","target_user_login":"dunctebot","created_by_user_id":"91097747","created_by":"duncte123"}}))
> ```

Maybe is fixed in 1.5.1?

**Comment by duncte123** [comment]
> > getting the same here for a mod event in version 1.5.0
> > ```json
> > Unparsable Message: MESSAGE|PubSubResponsePayload(
> > topic=chat_moderator_actions.711909329.91097747, 
> > message=PubSubResponsePayloadMessage(type=moderator_removed, messageData {"channel_id":"91097747","target_user_id":"711909329","moderation_action":"unmod","target_user_login":"dunctebot","created_by_user_id":"91097747","created_by":"duncte123"}, 
> > rawMessage={"type":"moderator_removed","data":{"channel_id":"91097747","target_user_id":"711909329","moderation_action":"unmod","target_user_login":"dunctebot","created_by_user_id":"91097747","created_by":"duncte123"}}))
> > ```
> 
> Maybe is fixed in 1.5.1?

Nope, just checked the source and it seems that the types `moderator_added` and `moderator_removed` are not listened for

https://github.com/twitch4j/twitch4j/blob/master/pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java#L499-L520

**Comment by duncte123** [comment]
Made a new issue since it seems unrelated https://github.com/twitch4j/twitch4j/issues/431

**Comment by iProdigy** [comment]
> getting the same here for a mod event in version 1.5.0

Yeah your log message is from that message type not being supported yet - the exception in this issue report originates from JGForms (which a library unrelated to twitch4j)
