### ISSUE TITLE
Cannot clear chat

### ISSUE THREAD

**Issue by Zeryther** [twitch4j/twitch4j#33]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered talking about it on [Discord](https://discord.gg/FQ5vgW3)
* [X] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/PhilippHeuer/twitch4j/issues) already

### Description
I tried to make a command that allows specific users to clear the chat if they're not moderators but instead of clearing the chat I just received a stack trace. I used the clearChat() method of the event to clear the chat.

### Steps to Reproduce
1. Use clearChat() on ChannelMessageEvent

**Expected behavior:** [What was supposed to happen] Bot should've cleared the chat

**Actual behavior:** [What actually happened] Bot did nothing

**Stacktrace (if applicable):** [link to the stacktrace] https://paste.md-5.net/pajevolile.avrasm

**Version affected:** [The version/commit you are using] cce583f

### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by stachu540** [comment]
Your issue is on your side?
Could you say, you bot have a Mod permission on your specific channel, right?

**Comment by stachu540** [comment]
Try to use `develop` build via JitPack

**Comment by Zeryther** [comment]
My bot is a moderator and when I use the develop build, I get the following error:
`[ERROR] m.p.t.e.UserEndpoint - RestException: RestError(error=Unauthorized, status=401, message=authentication failed)`

**Comment by stachu540** [comment]
Refresh token. Probably will be expired.

**Comment by PhilippHeuer** [comment]
You need to provide the access token and the refresh token in the TwitchClientBuilder to prevent this from happening again.

```
.withCredential("token")
.withCredentialRefreshToken("token")
```

**Comment by Zeryther** [comment]
I've added the tokens but it still doesn't work. The bot has no problems to send chat messages, the error only applies when I try to clear the chat.
