### ISSUE TITLE
Stream key + ingestion servers

### ISSUE THREAD

**Issue by mhackeras** [twitch4j/twitch4j#39]
Is it possible to retrieve stream key for user channel after auth ofc.? also retrieve ingestion servers ?

**Comment by stachu540** [comment]
Currently planned. No ETA.

**Comment by PhilippHeuer** [comment]
Actually there is, you can call `twitchClient.getChannelEndpoint("name").getChannelPrivilegied().getStreamKey()`

getChannelEndpoint either takes the name or the id as long.

You can get the list of ingest servers like this: `twitchClient.getIngestEndpoint().getIngestServer()`

**Comment by mhackeras** [comment]
Best twitch project. i didnt really have the time to play around.. but i ll give it a shoot right now!
