### ISSUE TITLE
TwitchClient close() doesn't shutdown scheduledThreadPoolExecutor

### ISSUE THREAD

**Issue by juberger** [twitch4j/twitch4j#390]
### Prerequisites

- [ ] If this is a question/suggestion, I have already considered discussing it on the [Discord Server](https://discord.gg/FQ5vgW3)
- [X] I have attempted to look for similar github issues already

### Expected Behavior

I'm creating chat bot with Tiwtch4j and JavaFX, when my application is stop I call twitchClient.close();

I expecting that all process of Twitch4j are shutdown.

### Current Behavior

When I stop my JavaFX application the java process is already running. 

After a few investigate the problem seem to be located in TwitchClient.close() method with the following code : 
`if (threadFactory.getNamingPattern().equalsIgnoreCase("twitch4j-%d")) {
                scheduledThreadPoolExecutor.shutdownNow();
            }`
threadFactory.getNamingPattern() is never equal to "twitch4j-%d".

Indeed when the scheduledThreadPoolExecutor is created in TwitchClient.build() method, a random String is added : 
`
if (scheduledThreadPoolExecutor == null) {
            scheduledThreadPoolExecutor = ThreadUtils.getDefaultScheduledThreadPoolExecutor("twitch4j-"+ RandomStringUtils.random(4, true, true), poolSize);
        }
`

### Environment

- **Library Version**:  1.5.0
- **IDE**: Eclipse
- **Java Version**: 16
- **Build Tools**: Maven 3.8.1
- **Operating System**: Windows 10

**Comment by iProdigy** [comment]
Thanks for reporting this bug - it should be fixed in the next release of twitch4j (no ETA yet).

In the meantime, a workaround for this issue is specifying your own `withScheduledThreadPoolExecutor` so you can manually call `ExecutorService#shutdownNow` on close

**Comment by juberger** [comment]
> 
> 
> Thanks for reporting this bug - it should be fixed in the next release of twitch4j (no ETA yet).
> 
> In the meantime, a workaround for this issue is specifying your own `withScheduledThreadPoolExecutor` so you can manually call `ExecutorService#shutdownNow` on close

Thanks, I will follow your workaround while winting the new release.
