### ISSUE TITLE
Mod/unmod events are not parsed in pubsub

### ISSUE THREAD

**Issue by duncte123** [twitch4j/twitch4j#431]
### Prerequisites

- [X] If this is a question/suggestion, I have already considered discussing it on the [Discord Server](https://discord.gg/FQ5vgW3)
- [X] I have attempted to look for similar github issues already

### Expected Behavior

the `ChannelModEvent` without any issues

### Current Behavior

An error gets printed to the console:
```json
30-08-2021 18:26:11 ReadingThr TwitchPubS WARN   Unparsable Message: MESSAGE|PubSubResponsePayload(
topic=chat_moderator_actions.711909329.91097747, 
message=PubSubResponsePayloadMessage(type=moderator_added, messageData={"channel_id":"91097747","target_user_id":"711909329","moderation_action":"mod","target_user_login":"dunctebot","created_by_user_id":"91097747","created_by":"duncte123"}, 
rawMessage={"type":"moderator_added","data":{"channel_id":"91097747","target_user_id":"711909329","moderation_action":"mod","target_user_login":"dunctebot","created_by_user_id":"91097747","created_by":"duncte123"}}))
30-08-2021 18:26:27 ReadingThr TwitchPubS WARN   Unparsable Message: MESSAGE|PubSubResponsePayload(
topic=chat_moderator_actions.711909329.91097747, 
message=PubSubResponsePayloadMessage(type=moderator_removed, messageData={"channel_id":"91097747","target_user_id":"711909329","moderation_action":"unmod","target_user_login":"dunctebot","created_by_user_id":"91097747","created_by":"duncte123"}, 
rawMessage={"type":"moderator_removed","data":{"channel_id":"91097747","target_user_id":"711909329","moderation_action":"unmod","target_user_login":"dunctebot","created_by_user_id":"91097747","created_by":"duncte123"}}))
```

### Environment

- **Library Version**: 1.5.1
- **IDE**: Intellij
- **Java Version**: 16.0.2
- **Build Tools**: Gradle
- **Operating System**: Ubuntu 20.04 LTS 

### Build Configuration

```kotlin
plugins {
    java
}

group = "com.dunctebot"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation(group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version = "2.12.4")
    implementation(group = "ch.qos.logback", name = "logback-classic", version = "1.2.3")
    implementation(group = "com.github.twitch4j", name = "twitch4j", version = "1.5.1")
    implementation(group = "com.squareup.okhttp3", name = "okhttp", version = "3.14.9")
}

tasks {
    wrapper {
        gradleVersion = "7.2"
        distributionType = Wrapper.DistributionType.ALL
    }
}
```

### Possible Solution

Implement the `moderator_added` and `moderator_removed` events in this part of the code

https://github.com/twitch4j/twitch4j/blob/master/pubsub/src/main/java/com/github/twitch4j/pubsub/TwitchPubSub.java#L499-L520

**Comment by iProdigy** [comment]
Sorry for the delay in following up on this - been busy irl and this problem goes much deeper than you'd expect.

To save you some reading, going to put some practical advice at the top: `ChannelModEvent` belongs to the chat module so it would not be fired by pubsub. Instead you want `ChatModerationEvent` (which you can see is fired in the highlighted section of the pubsub parsing you linked).

Now for the oddities: the messages sent over the pubsub websocket change depending on whether the mod/unmod command was issued from a third-party chat client or on the first-party twitch website.

If the mod/unmod command is sent directly over the irc socket, 2 pubsub messages are sent:

1. `type` of `moderator_added` and `data.moderation_action` is `mod`
2. `type` of `moderation_action` and `data.moderation_action` of `mod`

You're correct that the first message is not being parsed but the second message *is* correctly being parsed into an event. The first message does not contain any extra data that isn't provided in the second message. 

But here comes the problem; if the mod command is issued from the first-party site, *only* the first message is sent and not the more traditional second message that our library looks for. Given this twitch bug, I'll prioritize supporting the new `moderator_added` & `moderator_removed` types - thank you for providing the logs that contain example payloads.

But wait, there's more! The behavior for unmod was even weirder in my testing: I was not able to observe `moderator_removed` being sent over the socket. As a result, when `/unmod` was issued from the first-party site, I got *no* pubsub message. When `/unmod` was sent directly over the socket, the more traditional pubsub message *is* sent (`type` of `moderation_action` and `data.moderation_action` of `unmod`).

Did you think that's all? Nope! Also `/vip` and `/unvip` have similar oddities - thanks twitch 🤦

**Comment by duncte123** [comment]
Twitch pls NotLikeDIs

Thank you for implementing those two messages, it's highly appreciated
