### ISSUE TITLE
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/Module

### ISSUE THREAD

**Issue by Rebble69** [twitch4j/twitch4j#528]
am trying to create a spigot plug in with a built-in twitchbot, and am trying to enable helix. and am getting a NoClassDefFoundError for jackson databind. ive tried using diffrent versions of `com.fasterxml.jackson.core` as well as creating a standalone `TwitchHelix` Instance. but nothing seems to work 

```java
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/Module at com.github.twitch4j.helix.TwitchHelixBuilder.build(TwitchHelixBuilder.java:140)
```
```java
client = TwitchClientBuilder
                .builder()
                .withClientId("<CLIENTID>")
                .withClientSecret("<CLIENTSECRET>")
                .withChatAccount(<CREDENTIAL>)
                .withEnableChat(true)
                .withEnablePubSub(true)
                .withEnableHelix(true)
                .build();
```

**Comment by Katakurinna** [comment]
just asking, are you adding a twitch api to a spigot plugin? I think you should remodulate the architecture.

**Comment by Rebble69** [comment]
> 

sort of. the idea is to have twitch events trigger "actions" on the Minecraft server. such as channel point rewards.

**Comment by PhilippHeuer** [comment]
Your jar is most likely missing dependencies.

We have a example minecraft plugin here, maybe this is useful to you: https://github.com/twitch4j/twitch4j-minecraft-plugin
Specifially this part in the buildscript which is used to build a fatJar (jar with all used dependencies): https://github.com/twitch4j/twitch4j-minecraft-plugin/blob/main/build.gradle#L40-L46

**Comment by Rebble69** [comment]
> Your jar is most likely missing dependencies.
> 
> We have a example minecraft plugin here, maybe this is useful to you: https://github.com/twitch4j/twitch4j-minecraft-plugin Specifially this part in the buildscript which is used to build a fatJar (jar with all used dependencies): https://github.com/twitch4j/twitch4j-minecraft-plugin/blob/main/build.gradle#L40-L46

sorry for asking, ive tried making a fatjar with the `maven-assembly-plugin` and `maven-jar-plugin` but spigot dosent seem to be loading the jar. Any Advice?
(I prefer using maven because in the spigot development maven seems to be far more popular)

**Comment by iProdigy** [comment]
Add these dependencies to your pom:
```xml
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.13.1</version>
</dependency>
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.13.1</version>
</dependency>
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.13.1</version>
</dependency>
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-datatype-jsr310</artifactId>
    <version>2.13.1</version>
</dependency>
```

If your fat jar still doesn't work, can try using [maven-shade-plugin](https://gist.github.com/iProdigy/8b4c6dc4f959ce6e3fb57b0b673909c9)

**Comment by Rebble69** [comment]
that seems to work. thank you all!
