### ISSUE TITLE
Support tags on Streams

### ISSUE THREAD

**Issue by kiru** [twitch4j/twitch4j#64]
### Prerequisites
* [x ] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [x ] This issue specifically has something to do with Twitch4J
* [x ] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already
* [x ] I have read and understood the [contribution guidelines](https://github.com/twitch4j/twitch4j/blob/master/.github/CONTRIBUTING.md) and I accept them.

### Description

Twitch streams have a list of tags. There exists an endpoint get those ( https://dev.twitch.tv/docs/api/reference/#get-all-stream-tags ). This is not yet implemented by Twitch4J. 

See also: https://discuss.dev.twitch.tv/t/introducing-the-tags-api/19574

### Steps to Reproduce

---

**Expected behavior:** 

**Actual behavior:** 

**Stacktrace (if applicable):** 

**Version affected:**

**Comment by PhilippHeuer** [comment]
SomniumPrime added those functions, so i'm closing this issue. Will be part of the next alpha release `v1.0.0-alpha.11`
