### ISSUE TITLE
Possible bug: It seems that multiple chat-tags map to the EMOTE ChannelState

### ISSUE THREAD

**Issue by SomniumPrime** [twitch4j/twitch4j#65]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [X] This issue specifically has something to do with Twitch4J
* [X] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already
* [X] I have read and understood the [contribution guidelines](https://github.com/twitch4j/twitch4j/blob/master/.github/CONTRIBUTING.md) and I accept them.

### Description 
Possible bug: It seems that multiple chat-tags map to the EMOTE ChannelState
In:
IRCEventHandler.onChannelState

    case "emote-only":
        states.put(ChannelStateEvent.ChannelState.EMOTE, v.equals("1"));

    case "r9k":
        states.put(ChannelStateEvent.ChannelState.EMOTE, v.equals("1"));

    case "subs-only":
        states.put(ChannelStateEvent.ChannelState.EMOTE, v.equals("1"));

### Solutions
Should these have been ChannelState.R9K and ChannelState.SUBSCRIBERS respectively?

**Comment by PhilippHeuer** [comment]
You'r right - this was a mistake, thanks for creating the issue. Is fixed in develop in will be in the next release.
