### ISSUE TITLE
Consider adding the users endpoint to TwitchKraken

### ISSUE THREAD

**Issue by SomniumPrime** [twitch4j/twitch4j#66]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [X] This issue specifically has something to do with Twitch4J
* [X] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already
* [X] I have read and understood the [contribution guidelines](https://github.com/twitch4j/twitch4j/blob/master/.github/CONTRIBUTING.md) and I accept them.

### Description 

The Helix users endpoint still does not contain the "created_at" property. This property is very useful when trying to combat channel spawn, by helping to identify newly created spam accounts.

### Solutions
Although the Kraken endpoints are deprecated, consider adding the https://api.twitch.tv/kraken/users endpoint to TwitchKraken.java, so that the "created_at" property of users can be looked up. 

### Alternatives

Apparently there is currently no alternate way to get this information from the Twitch APIs

**Comment by PhilippHeuer** [comment]
Thanks for the pull request ;)
