### ISSUE TITLE
Consider adding an optional authorization parameter to the Helix unauthenticated metods, to alleviate rate limits.

### ISSUE THREAD

**Issue by SomniumPrime** [twitch4j/twitch4j#67]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [X] This issue specifically has something to do with Twitch4J
* [X] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already
* [X] I have read and understood the [contribution guidelines](https://github.com/twitch4j/twitch4j/blob/master/.github/CONTRIBUTING.md) and I accept them.

### Description 
Accessing the unauthenticated Helix-api methods without a bearer token, significantly reduces the api limits.
Consider adding auth-token as an optional parameter to the unauthenticated methods.

### Solutions

Consider adding an optional authorization parameter, to the TwitchHelix.java methods which currently does not require it.

This since adding a valid bearer token (either user access token or application specific app access token) will increase the rate limit from 30 calls per minute to 800 calls per minute (per token). This would make it more efficient to poll for e.g. follower changes. This could also be used to optimize the TwitchClientHelper.

### Alternatives

Since the unauthenticated rate limits are globally enforced on a per IP-address level, currently the only workaround is either to use longer polling intervals, or several external IP-adresses. Neither of which will scale very well, especially if polling e.g. followers for multiple channels, since the limits will be enforced across all the channels (instead on a per-user basis).

### Additional context

API limits as described here:
https://dev.twitch.tv/docs/api/guide/#rate-limits

**Comment by PhilippHeuer** [comment]
Thanks again, just merged it into `develop`.
