### ISSUE TITLE
ChannelChangeGameEvent and ChannelChangeTitleEvent don't trigger

### ISSUE THREAD

**Issue by ilotterytea** [twitch4j/twitch4j#708]
### Prerequisites

- [ ] If this is a question/suggestion, I have already considered discussing it on the [Discord Server](https://discord.gg/FQ5vgW3)
- [X] I have attempted to look for similar github issues already

### Expected Behavior

I expected that when I changed the stream title or category, it would trigger the related events in the bot.
```java
OAuth2Credential credential = new OAuth2Credential("twitch", properties.getProperty("OAUTH2_TOKEN"));
TwitchClient client = TwitchClientBuilder.builder()
                .withChatAccount(credential)
                .withDefaultAuthToken(credential)
                .withEnableTMI(true)
                .withEnableChat(true)
                .withClientId(properties.getProperty("CLIENT_ID"))
                .withClientSecret(properties.getProperty("CLIENT_SECRET"))
                .withEnableHelix(true)
                .withHelperThreadDelay(1000)
                .build();

client.getClientHelper().enableStreamEventListener("ilotterytea");

client.getEventManager().onEvent(ChannelGoOfflineEvent.class, e -> {
            System.out.println("offline " + e.toString());
});
client.getEventManager().onEvent(ChannelGoLiveEvent.class, e -> {
            System.out.println("live " + e.toString());
});
client.getEventManager().onEvent(ChannelChangeTitleEvent.class, e -> {
            System.out.println("title " + e.toString());
});
client.getEventManager().onEvent(ChannelChangeGameEvent.class, e -> {
            System.out.println("game " + e.toString());
});
```

### Current Behavior

ChannelChangeTitleEvent does not trigger when you change the stream title, and the same goes for ChannelChangeGameEvent, which does not trigger when you change the category of the stream. Of the 4 events, only ChannelGoLiveEvent and ChannelGoOfflineEvent trigger.

### Environment

- **Library Version**: 1.13.0
- **IDE**: Intellij IDEA 2022.3
- **Java Version**: 1.8.0_352
- **Build Tools**: Gradle 7.5.1
- **Operating System**: Arch Linux 6.1.4-zen2-1-zen (x86_64)

### Build Configuration

```groovy
plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
}

group 'kz.ilotterytea'
version '1.0'

ext {
    artifact = 'huinyabot'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.github.twitch4j:twitch4j:1.13.0'
    implementation 'ch.qos.logback:logback-classic:1.3.5'
    implementation 'com.google.code.gson:gson:2.10'
    implementation 'org.jsoup:jsoup:1.15.3'
    implementation 'org.java-websocket:Java-WebSocket:1.5.3'
    implementation 'com.squareup.okhttp3:okhttp:4.10.0'
}

test {
    useJUnitPlatform()
}

java {
    withSourcesJar()
}

application {
    mainClass = "kz.ilotterytea.bot.Main"
}

shadowJar {
    archiveFileName = "${artifact}.jar"
}
```

**Comment by iProdigy** [comment]
Note: those change game/title events only fire *if* the channel is live

**Comment by ilotterytea** [comment]
> Note: those change game/title events only fire _if_ the channel is live

Thanks for the reply! It would be great if this information appeared on the [ChannelChangeGameEvent](https://twitch4j.github.io/events/channel-change-game-event/) and [ChannelChangeTitleEvent](https://twitch4j.github.io/events/channel-change-title-event) pages, because it's not mentioned in the Twitch4j wiki.

**Comment by antihack3r** [comment]
i checked. "channel.update" notification fires even if the channel isn't live!
