### ISSUE TITLE
Twitch get stream key

### ISSUE THREAD

**Issue by mhackeras** [twitch4j/twitch4j#73]
is there a possibility to get twitch live stream key with your library?

**Comment by PhilippHeuer** [comment]
No it's not supported yet, and as it's not available in helix yet afaik it would have to be added to the kraken module.

Will leave this open as feature request.

**Comment by mhackeras** [comment]
so for now it's really impossible to get the stream key in any way?? you cant even use older apis?
when it will become available  i will contact you or even help you with a pull request

**Comment by PhilippHeuer** [comment]
It's impossible with the new api (helix), but this call can retrieve a users stream key (old api - kraken): https://dev.twitch.tv/docs/v5/reference/channels/#get-channel
So we could temporarily add it to kraken until it's supported on helix.

**Comment by mhackeras** [comment]
This project seems promising.
I start exploring now.
My main purpose is to use auth, change title etc in livestream and get the stream key.
if you could point me out on how to use this i would be super glad.

**Comment by mhackeras** [comment]
Hey @PhilippHeuer  how is the project going?
Do we have any news on getting stream key?

**Comment by PhilippHeuer** [comment]
Closing this as the streamkey helix endpoint was added in the latest release.
