### ISSUE TITLE
Twitch API v5 - Endpoint: Channel Feed

### ISSUE THREAD

**Issue by PhilippHeuer** [twitch4j/twitch4j#8]
### Description
Creating a channel feed endpoint and adding the following methods:

| Endpoint | Description |
| --- | --- |
| [Get Multiple Feed Posts](#get-multiple-feed-posts) | Gets posts from a specified channel feed. |
| [Get Feed Post](#get-feed-post) | Gets a specified post from a specified channel feed. |
| [Create Feed Post](#create-feed-post) | Creates a post in a specified channel feed. The content of the post is specified in the request body, with a _required_ `content` parameter. |
| [Delete Feed Post](#delete-feed-post) | Deletes a specified post in a specified channel feed. |
| [Create Reaction to a Feed Post](#create-reaction-to-a-feed-post) | Creates a reaction to a specified post in a specified channel feed. The reaction is specified by an emote value, which is either an ID (for example, “25” is Kappa) or the string “endorse” (which corresponds to a default face emote). |
| [Delete Reaction to a Feed Post](#delete-reaction-to-a-feed-post) | Deletes a specified reaction to a specified post in a specified channel feed. The reaction is specified by an emote ID (for example, “25” is Kappa) or the string “endorse” (which corresponds to a default face emote). |
| [Get Feed Comments](#get-feed-comments) | Gets all comments on a specified post in a specified channel feed. |
| [Create Feed Comment](#create-feed-comment) | Creates a comment to a specified post in a specified channel feed. The comment content can be specified either as a query-string parameter or in the request body (in x-www-form-urlencoded format). |
| [Delete Feed Comment](#delete-feed-comment) | Deletes a specified comment on a specified post in a specified channel feed. |
| [Create Reaction to a Feed Comment](#create-reaction-to-a-feed-comment) | Creates a reaction to a specified comment on a specified post in a specified channel feed. The reaction is specified by an emote value, which is either an ID (for example, “25” is Kappa) or the string “endorse” (which corresponds to a default face emote). |
| [Delete Reaction to a Feed Comment](#delete-reaction-to-a-feed-comment) | Deletes a reaction to a specified comment on a specified post in a specified channel feed. The reaction is specified by an emote value, which is either an ID (for example, “25” is Kappa) or the string “endorse” (which corresponds to a default face emote). |

### Additional Information
Link: https://dev.twitch.tv/docs/v5/reference/channel-feed/

**Comment by stachu540** [comment]
Closed by #50
