### ISSUE TITLE
Jcenter JARs all have old me.philippheuer class names

### ISSUE THREAD

**Issue by mattjs** [twitch4j/twitch4j#81]
I was trying to use Jcenter to import this library into my project but all of the JAR files there have old `me.philippheuer` class names

I downloaded a few of them to manually inspect the JAR and ran the following command

`jar tvf twitch4j.jar`

```
     0 Wed Sep 19 17:38:42 MDT 2018 META-INF/
    25 Wed Sep 19 17:38:42 MDT 2018 META-INF/MANIFEST.MF
     0 Wed Sep 19 17:38:40 MDT 2018 me/
     0 Wed Sep 19 17:38:40 MDT 2018 me/philippheuer/
     0 Wed Sep 19 17:38:42 MDT 2018 me/philippheuer/twitch4j/
     0 Wed Sep 19 17:38:42 MDT 2018 me/philippheuer/twitch4j/model/
  1852 Wed Sep 19 17:38:42 MDT 2018 me/philippheuer/twitch4j/model/BlockList.class
  2103 Wed Sep 19 17:38:42 MDT 2018 me/philippheuer/twitch4j/model/TopGame.class
   ...
```

Am I doing something wrong? Is Jcenter not being used anymore?

I checked both of these to make sure I wasn't hitting the wrong one due to capitalization.
https://jcenter.bintray.com/com/github/twitch4j/twitch4j/v0.12.0/:twitch4j-v0.12.0.jar
https://jcenter.bintray.com/com/github/twitch4j/Twitch4J/v0.12.0/:Twitch4J-v0.12.0.jar

**Comment by PhilippHeuer** [comment]
The `v0.x.x` are the old versions, the recent ones are `v1.0.0-alpha.x` which are only available on the jfrog snapshot repository (kinda like the staging area for jcenter) right now -> check out https://twitch4j.gitlab.io/twitch4j/getting-started/installation/.

Link to the Jars: https://oss.jfrog.org/artifactory/libs-release/com/github/twitch4j/

It is about time to make a official 1.0.0 releaese on jcenter though.

**Comment by mattjs** [comment]
Thanks Phillip!
