### ISSUE TITLE
A NullPointerException is thrown instead of a more specific exception for some methods when incorrect authentication is provided

### ISSUE THREAD

**Issue by sg4e** [twitch4j/twitch4j#82]
### Prerequisites
* [x] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [x] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description

At least `twitchClient.getHelix().replaceStreamTags(...).execute()` generates a NullPointerException when a bogus auth token is provided instead of a `com.github.twitch4j.common.exception.UnauthorizedException` like the graceful error handling is intended to throw.
### Steps to Reproduce

```java
         // chat credential
        OAuth2Credential credential = new OAuth2Credential("twitch", "bogustoken");

        // twitch client
        twitchClient = TwitchClientBuilder.builder()
                .withClientId(API_CLIENT_ID)
                .withClientSecret(API_CLIENT_SECRET)
                .withEnableChat(true)
                .withEnableHelix(true)
                .withChatAccount(credential)
                .build();
        twitchClient.getHelix().replaceStreamTags("bogustoken", 73758417L, new ArrayList<>()).execute();
```

**Expected behavior:** 
`com.github.twitch4j.common.exception.UnauthorizedException`

**Actual behavior:** 
`java.lang.NullPointerException`

**Version affected:** 
8912db26c7ca06e1ac16745efe3787b741edaab4

**Comment by sg4e** [comment]
PR fix: #83

**Comment by PhilippHeuer** [comment]
Merged it, but i still need to find out why the response body was dropped by feign - it's prob. the http client used by feign.

**Comment by PhilippHeuer** [comment]
Yeah, the default feign http client uses HttpURLConnection to send requests and HttpURLConnection will make the response body null when the response code is 401 or 407.`.

I switched to okhttp as client so that should fix it.
