### ISSUE TITLE
Error with Helix getSubscriptions()

### ISSUE THREAD

**Issue by Riverxik** [twitch4j/twitch4j#84]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [x] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description

I'm trying to get channel subscriptions with helix:
```java
SubscriptionList subList = twitchClient.getHelix().getSubscriptions(
                myAccessToken,
                channelId,
                null,
                null,
                100
        ).execute();
```
but i getting this error:
```java
Caused by: feign.FeignException: Cannot deserialize value of type `java.lang.Integer` from String "ByterbrodTV": not a valid Integer value
```

### Steps to Reproduce
1. Find partner channel.
2. Get access token for it.
3. Try to get list of subscribers with helix

---

**Expected behavior:** 
I expect getting list of subscriptions

**Actual behavior:** 
InvalidFormatException

**Stacktrace (if applicable):** 

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Integer` from String "ByterbrodTV": not a valid Integer value
 at [Source: java.io.BufferedReader@63502b8e; line: 1, column: 175] (through reference chain: com.github.twitch4j.helix.domain.SubscriptionList["data"]->java.util.ArrayList[0]->com.github.twitch4j.helix.domain.Subscription["user_name"])
```
**Version affected:** 

I trying this on `1.0.0-alpha.11` and `1.0.0-alpha.14`
### Additional Information 

I think `userName` must be String in this case
`package com.github.twitch4j.helix.domain;`
![image](https://user-images.githubusercontent.com/28196994/61349798-ccfd2a80-a87e-11e9-8b92-f14248e22a9e.png)

P.S. 
1. There is good accesstoken. I trying to do it manually - it works.
2. I also get working with kraken but kraken is not stable for me and sometimes throwing me time-out and no fallback exception.

**Comment by Riverxik** [comment]
I talking about: d1b0e58

**Comment by PhilippHeuer** [comment]
I pushed a new `1.0.0-alpha.15` which has this fixed. Thanks for the report.
