### ISSUE TITLE
ChannelGoLiveEvent doesn't trigger everytime

### ISSUE THREAD

**Issue by jB-Maxoux** [twitch4j/twitch4j#86]
### Prerequisites
* [ ] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [x] This issue specifically has something to do with Twitch4J
* [x] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description
I don't know exactly why, but ChannelGoLiveEvent doesn't trigger everytime. Sometimes it works 3 days without any problem, and then nothing. However, ChannelGoOfflineEvent works perfectly.
It seems to happen everytime a replay is started on the channel.
Here is the code »
`twitchClient.getEventManager().onEvent(ChannelGoOfflineEvent.class).subscribe((channelGoOfflineEvent) -> {/*insert code*/});`

Before you ask, no, there isn't any errors, and I already tried to put only a sysout and it does not trigger.

### Steps to Reproduce

1. Add the code line in a method which is triggered at programs startup.
2. Don't forget to add `twitchClient.getClientHelper().enableStreamEventListener("your_channel");` before registering any events related to live events.
3. Launch a live, the event should trigger as excepted.
4. Launch a replay, and wait until it finishes or stop it.
5. Launch a live, the event shouldn't trigger.
6. This is **optional**, but you can try restarting the program, relaunch the live, and it should work again.

---

**Expected behavior:** 

The event was supposed to trigger.
**Actual behavior:** 

The event isn't triggered.

**Version affected:** 

1.0.0-alpha.11

**Comment by boostchicken** [comment]
Can confirm this is happening, had to roll away from this code. Believe its related to the cache checking logic.

**Comment by PhilippHeuer** [comment]
Thanks for the report - i will try to reproduce this today. But it definitly sounds like a caching issue somehow related to replays.

**Comment by jB-Maxoux** [comment]
Any news ?

**Comment by PhilippHeuer** [comment]
A replay shouldn't have any effect on goLive/goOffline Events, because the api call (getStreams on helix) only returns results for actual livestreams, not replays (look the same as offline).
But i noticed one field in the response of getStreams: `Stream type: "live" or "" (in case of error).`. Not quite sure what a possible error would be here, but it's a good idea to check that the value is actually `live`.

The 2nd possibility is that it's a caching issue, so i added caffeine as caching library.

I pushed it as `v1.0.0-alpha.16`. Maybe you can check it and give feedback.

**Comment by jB-Maxoux** [comment]
The problem seems fixed.
Thanks you very much :)

Also, it could be nice if the GoLiveEvent has a "LiveType variable" which would be an enum and basicly have 2 element, LIVE, and REPLAY. This will let you do something like
`if(event.getLiveType().equals(LiveType.LIVE)){}` and/or `if(event.getLiveType().equals(LiveType.REPLAY)){}` :)
Same for the GoOfflineEvent :)

Just leaving an idea :D
