### ISSUE TITLE
Out of memory on 1.0.0-alpha.15 using twtich chat

### ISSUE THREAD

**Issue by Sammers21** [twitch4j/twitch4j#87]
Here is what Eclipse Memory Analyzer says:

![image](https://user-images.githubusercontent.com/16746106/62164094-74b93480-b324-11e9-8bad-9246e3a7c6d4.png)

I will not provide a precise reproducer for the issue, but I just want you to know about the bug existence.

The bug occurs when you have joined a lot of chats(30+ in my case) and then some of them goes offline. Heap size starts increasing:

![image](https://user-images.githubusercontent.com/16746106/62164309-daa5bc00-b324-11e9-8dd0-758b459e42fb.png)

**Comment by Sammers21** [comment]
Note: this bug did not occur on 1.0.0-alpha.13

**Comment by PhilippHeuer** [comment]
I suspect that your app wasn't able to keep up with the events which caused them to pile up in the queue, which was not limited in size until now.

I added a restriction, that will also drop events once we hit a limit (16384 for now). Also it's now customizable in the TwitchClientBuilder how many threads should be used to process events and how big the queue can be at max.

**Comment by Sammers21** [comment]
> I suspect that your app wasn't able to keep up with the events which caused them to pile up in the queue, which was not limited in size until now.


@PhilippHeuer , you are right, the CPU usage is 100%:
![image](https://user-images.githubusercontent.com/16746106/62320895-16b65980-b4aa-11e9-82a6-71de941ab475.png)
