### ISSUE TITLE
TMI Chatters - Not Found Exception

### ISSUE THREAD

**Issue by Dustinhoefer** [twitch4j/twitch4j#885]
### Prerequisites

- [X] If this is a question/suggestion, I have already considered discussing it on the [Discord Server](https://discord.gg/FQ5vgW3)
- [X] I have attempted to look for similar github issues already

### Expected Behavior

Chatters should be found

### Current Behavior

No users are found

### Log output / Stacktrace

```txt
Caused by: com.github.twitch4j.common.exception.NotFoundException: Exception Context:
	[1:requestUrl=https://tmi.twitch.tv/group/user/[channelname]/chatters]
	[2:requestMethod=GET]
	[3:responseBody=Not Found]
```

### Environment

- **Library Version**: 0.18
- **IDE**:  Intellij
- **Java Version**:  20
- **Build Tools**:  Maven
- **Operating System**:  Windows

**Comment by iProdigy** [comment]
The [javadoc](https://twitch4j.github.io/javadoc/com/github/twitch4j/tmi/TwitchMessagingInterface.html) on `TwitchMessagingInterface.html#getChatters` states: "This method will be permanently shutdown by Twitch on 2023-04-03 in favor of TwitchHelix#getChatters"

To switch to the [helix equivalent](https://twitch4j.github.io/javadoc/com/github/twitch4j/helix/TwitchHelix.html#getChatters(java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String)), you will need a user access token from the broadcaster or a moderator with the `moderator:read:chatters` scope.

Alternatively, for small channels (<1k concurrent chatters), you can use irc [join](https://twitch4j.github.io/javadoc/com/github/twitch4j/chat/events/channel/ChannelJoinEvent.html)/[part](https://twitch4j.github.io/javadoc/com/github/twitch4j/chat/events/channel/ChannelLeaveEvent.html) events (but this is not as reliable).

Feel free to join our Discord for more clarification
