### ISSUE TITLE
Not possible to listen for Channel Point Redeemed Events

### ISSUE THREAD

**Issue by Dustinhoefer** [twitch4j/twitch4j#886]
### Prerequisites

- [X] If this is a question/suggestion, I have already considered discussing it on the [Discord Server](https://discord.gg/FQ5vgW3)
- [X] I have attempted to look for similar github issues already

### Expected Behavior

I would expect to be able to Listen to something like this:

twitchClient.getEventManager().onEvent(ChannelPointsRedemptionEvent.class, event -> {
            System.out.println("Received event: 3");
        });

### Current Behavior

This is never triggered :/

### Environment

- **Library Version**:  1.18
- **IDE**:  Intellij
- **Java Version**: 17
- **Build Tools**: maven
- **Operating System**: Windows 11

**Comment by Dustinhoefer** [comment]
Also, not even the IRCMessageEvent is triggered when redeeming

**Comment by iProdigy** [comment]
`ChannelPointsRedemptionEvent` (superclass of `RewardRedeemedEvent`) is a pubsub event. This requires [`ITwitchPubSub#listenForChannelPointsRedemptionEvents`](https://twitch4j.github.io/javadoc/com/github/twitch4j/pubsub/ITwitchPubSub.html#listenForChannelPointsRedemptionEvents(com.github.philippheuer.credentialmanager.domain.OAuth2Credential,java.lang.String)) to be called. Be sure you're passing the channel *id* (not name) to the second arg. You should also log `PubSubListenResponseEvent` to ensure Twitch is not rejecting your listen request.

In terms of chat events, `ChannelMessageEvent`/`IRCMessageEvent` would only be triggered if the reward redemption includes user text input. PubSub receives all *custom* reward redemption, regardless of whether they include user text input. Automatic rewards created by twitch (e.g., redeem an emote) do not trigger pubsub or irc events.
