### ISSUE TITLE
KrakenTeam model is missing team members (users)

### ISSUE THREAD

**Issue by tedyoung** [twitch4j/twitch4j#95]
### Prerequisites
* [X] If this is a question/suggestion, I have already considered discuss it on [Discord Server](https://discord.gg/FQ5vgW3)
* [X] This issue specifically has something to do with Twitch4J
* [X] I have attempted to [look for similar issues](https://github.com/twitch4j/twitch4j/issues) already

### Description
The "get team" API endpoint supports an array of users who belong to that team (see https://dev.twitch.tv/docs/v5/reference/teams/#get-team for details), but the current implementation in Twitch4J does not have that information.

### To Fix

The `KrakenTeam` model needs to have a `List<KrakenUser> users` added to it to support the missing information.

**Version affected:** 
1.0.0-alpha16

### Additional Information 
I have fixed this locally for me and can submit a Pull Request.

**Comment by PhilippHeuer** [comment]
Thanks for the report.
I would be happy to merge this if you create a PR :)

**Comment by PhilippHeuer** [comment]
Thanks, closing this as pr #95 was merged.
