### ISSUE TITLE
Support Twich CLI Mock-API authentication

### ISSUE THREAD

**Issue by Deroin** [twitch4j/twitch4j#989]
### Prerequisites

- [ ] If this is a question/suggestion, I have already considered discussing it on the [Discord Server](https://discord.gg/FQ5vgW3)
- [X] I have attempted to look for similar github issues already

### Description

Currently when creating a `HelixClient` it is possible to specify a `baseUrl` in order to switch from the production Twitch API host to a locally running Mock API from the [Twitch CLI](https://dev.twitch.tv/docs/cli) utility.

Unfortunately further down the line `TwitchIdentityProvider`instances are created for various components and the authentication URLs here are hard-coded to run against the production Twitch Servers. 

For a full local testing setup it would be great to be able to switch this to the Mock API as well.

**Comment by iProdigy** [comment]
This is now supported in https://github.com/twitch4j/twitch4j/releases/tag/v1.21.0

When `TwitchHelixBuilder.MOCK_BASE_URL` is used, the `TwitchIdentityProvider` instances automatically are pointed at `TwitchIdentityProvider.CLI_MOCK_BASE_URL`
